name: bitlabs
description: BitLabs offers the opportunity to monetize your app with rewarded surveys easily.
version: 3.0.0
repository: https://github.com/BitBurst-GmbH/bitlabs-flutter

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  advertising_id: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  url_launcher: ^6.1.2
  webview_flutter: ^4.10.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  webview_flutter_android: ^4.3.1
  device_info_plus: ^11.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  test: ^1.24.1
  mockito: ^5.4.2
