name: bitlabs
description: BitLabs offers the opportunity to monetize your app with rewarded surveys easily.
version: 2.2.0
repository: https://github.com/BitBurst-GmbH/bitlabs-flutter

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  advertising_id: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  http: ^1.1.0
  url_launcher: ^6.1.2
  webview_flutter: ^4.2.1
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  test: ^1.24.1
  mockito: ^5.4.2
