name: bitlabs
description: BitLabs offers the opportunity to monetize your app with rewarded surveys easily.
version: 3.0.1
repository: https://github.com/BitBurst-GmbH/bitlabs-flutter

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.3.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BitlabsPlugin
      android:
        pluginClass: BitlabsPlugin
        package: ai.bitlabs.bitlabs_flutter

