name: bitlabs
description: BitLabs offers the opportunity to monetize your app with rewarded surveys easily.
version: 2.0.0
repository: https://github.com/BitBurst-GmbH/bitlabs-flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  advertising_id: ^2.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.1.2
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.1