name: Tests

on: [ push ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Run simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15 Pro'

      - name: Run Integration tests
        run: |
          cd example/
          flutter test integration_test